import initScrollSuave from "./modules/scrol-suave.js";
import initAnimaScrol from "./modules/anima-scroll.js";
import initAccordion from "./modules/accordion.js";
import initTabNav from "./modules/tab-nav.js";
import initMocdal from "./modules/modal.js";
import initTooltip from "./modules/tooltip.js";
import initDropdownMenu from "./modules/dropdown-menu.js";
import initMenuHamburguer from "./modules/menu-hamburguer.js";
import initAnimaNumeros from "./modules/anima-numeros.js";
import initHorarioFuncionamento from "./modules/horario-funcionamento.js";

initScrollSuave();
initAnimaScrol();
initAccordion();
initTabNav();
initMocdal();
initTooltip();
initDropdownMenu();
initMenuHamburguer();
initAnimaNumeros();
initHorarioFuncionamento();
